package com.shoestore.entity;
// Generated Apr 20, 2024, 2:20:15 PM by Hibernate Tools 4.3.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * OrderDetail generated by hbm2java
 */
@Entity
@Table(name = "order_detail", catalog = "shoestoredb")
@NamedQueries({
	@NamedQuery(name = "OrderDetail.listBestSelling", query = "SELECT od.shoe FROM OrderDetail od GROUP BY od.shoe.shoeId ORDER BY SUM(od.quantity) DESC"),
	@NamedQuery(name = "OrderDetail.countByShoe", query = "SELECT COUNT(*) FROM OrderDetail od WHERE od.shoe.shoeId = :shoeId AND od.id.shoeOrder.status = 'Processing'")
})
public class OrderDetail implements java.io.Serializable {

	private OrderDetailId id = new OrderDetailId();
	private Shoe shoe;
	private ShoeOrder shoeOrder;
	private int quantity;
	private float subTotal;

	public OrderDetail() {
	}

	public OrderDetail(OrderDetailId id, Shoe shoe, ShoeOrder shoeOrder, int quantity, float subTotal) {
		this.id = id;
		this.shoe = shoe;
		this.shoeOrder = shoeOrder;
		this.quantity = quantity;
		this.subTotal = subTotal;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "orderId", column = @Column(name = "order_id", nullable = false)),
			@AttributeOverride(name = "shoeId", column = @Column(name = "shoe_id", nullable = false)) })
	public OrderDetailId getId() {
		return this.id;
	}

	public void setId(OrderDetailId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "shoe_id", nullable = false, insertable = false, updatable = false)
	public Shoe getShoe() {
		return this.shoe;
	}

	public void setShoe(Shoe shoe) {
		this.shoe = shoe;
		this.id.setShoe(shoe);
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_id", nullable = false, insertable = false, updatable = false)
	public ShoeOrder getShoeOrder() {
		return this.shoeOrder;
	}

	public void setShoeOrder(ShoeOrder shoeOrder) {
		this.shoeOrder = shoeOrder;
		this.id.setShoeOrder(shoeOrder);
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "sub_total", nullable = false, precision = 12, scale = 0)
	public float getSubTotal() {
		return this.subTotal;
	}

	public void setSubTotal(float subTotal) {
		this.subTotal = subTotal;
	}
	
}
