package com.shoestore.entity;
// Generated Apr 20, 2024, 2:20:15 PM by Hibernate Tools 4.3.6.Final

import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

/**
 * OrderDetailId generated by hbm2java
 */
@Embeddable
public class OrderDetailId implements java.io.Serializable {
	private Shoe shoe;
	private ShoeOrder shoeOrder;
	
	public OrderDetailId() {
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "shoe_id", nullable = false, insertable = false, updatable = false)
	public Shoe getShoe() {
		return this.shoe;
	}

	public void setShoe(Shoe shoe) {
		this.shoe = shoe;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_id", nullable = false, insertable = false, updatable = false)
	public ShoeOrder getShoeOrder() {
		return this.shoeOrder;
	}

	public void setShoeOrder(ShoeOrder shoeOrder) {
		this.shoeOrder = shoeOrder;
	}

	@Override
	public int hashCode() {
		return Objects.hash(shoe, shoeOrder);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		OrderDetailId other = (OrderDetailId) obj;
		return Objects.equals(shoe, other.shoe) && Objects.equals(shoeOrder, other.shoeOrder);
	}
}
